---
site_name: Koptan's Documentation
repo_url: https://github.com/felukka/koptan
site_url: https://koptan.felukka.org
nav:
  - Home: index.md
  - Getting started:
      - Prerequisites: getting-started/prerequisites.md
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Resources:
      - Service: resources/service.md
      - CI: resources/ci.md
      - CD: resources/cd.md
      - CIPlugin: resources/ciplugin.md
      - Alert: resources/alert.md
      - SelfService: resources/selfservice.md
  - Helm charts:
      - koptan: helm/koptan.md
      - koptan-ui: helm/koptan-ui.md
  - UI: ui/overview.md
  - Configuration:
      - Operator: configuration/operator.md
      - Security: configuration/security.md
  - Reference:
      - Troubleshooting: reference/troubleshooting.md
      - FAQ: reference/faq.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  # TODO: Replace with real logos
  logo: assets/koptan.png
  favicon: assets/koptan.png
  font:
    text: IBM Plex Sans Condensed
    code: JetBrains Mono
  features:
    - navigation.footer
    - search.highlight
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - content.tabs.link
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-night
        name: Light mode
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
copyright: Copyright &copy; 2026 Felukka.org
