# This rule is not used by the project koptan itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to felukka.felukka.sh resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: koptan
    app.kubernetes.io/managed-by: kustomize
  name: habel-viewer-role
rules:
- apiGroups:
  - felukka.felukka.sh
  resources:
  - habels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - felukka.felukka.sh
  resources:
  - habels/status
  verbs:
  - get
