---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - koptan.felukka.org
  resources:
  - cds
  - cis
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - koptan.felukka.org
  resources:
  - cds/finalizers
  - cis/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - koptan.felukka.org
  resources:
  - cds/status
  - cis/status
  - services/status
  verbs:
  - get
  - patch
  - update
