# This rule is not used by the project koptan itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to koptan.felukka.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: koptan
    app.kubernetes.io/managed-by: kustomize
  name: voyage-viewer-role
rules:
  - apiGroups:
      - koptan.felukka.org
    resources:
      - voyages
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - koptan.felukka.org
    resources:
      - voyages/status
    verbs:
      - get
