apiVersion: koptan.felukka.org/v1alpha
kind: GoApp
metadata:
  labels:
    app.kubernetes.io/name: koptan
    app.kubernetes.io/managed-by: kustomize
  name: goapp-sample
spec:
  # TODO(user): Add fields here
