# syntax=docker/dockerfile:1
# Generated by Koptan: .NET 9.0, project src/Api/Api.csproj.
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish "src/Api/Api.csproj" -c Release -o /out -p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /out .
ENV PORT=8080 ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
USER $APP_UID
CMD ["dotnet","Shop.Api.dll"]
