# syntax=docker/dockerfile:1
# Generated by Koptan: Go 1.23, main package ./cmd/shop.
FROM golang:1.23-bookworm AS build
WORKDIR /src
COPY . .
RUN go mod download && mkdir -p /out && CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/app ./cmd/shop

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/app /app
ENV PORT=8080
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/app"]
