# syntax=docker/dockerfile:1
# Generated by Koptan: Go 1.22, main package ..
FROM golang:1.22-bookworm AS build
WORKDIR /src
COPY . .
RUN go mod download && mkdir -p /out && CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/app .

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/app /app
ENV PORT=8080
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/app"]
