# syntax=docker/dockerfile:1
# Generated by Koptan: Java 17 with maven.
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /src
COPY . .
RUN mvn -B -q package -DskipTests \
    && jar="$(find target -maxdepth 1 -name '*.jar' ! -name '*-plain.jar' \
        ! -name '*-sources.jar' ! -name '*-javadoc.jar' ! -name 'original-*' | head -n1)" \
    && test -n "$jar" && cp "$jar" /app.jar

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app.jar /app/app.jar
ENV PORT=8080 JAVA_OPTS=""
EXPOSE 8080
USER 10001:10001
CMD ["sh","-c","exec java $JAVA_OPTS -Dserver.port=${PORT} -jar /app/app.jar"]
