# syntax=docker/dockerfile:1
# Generated by Koptan: Java 25 with gradle.
FROM eclipse-temurin:25-jdk AS build
WORKDIR /src
COPY . .
RUN chmod +x gradlew && ./gradlew --no-daemon -q build -x test \
    && jar="$(find build/libs -maxdepth 1 -name '*.jar' ! -name '*-plain.jar' \
        ! -name '*-sources.jar' ! -name '*-javadoc.jar' ! -name 'original-*' | head -n1)" \
    && test -n "$jar" && cp "$jar" /app.jar

FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=build /app.jar /app/app.jar
ENV PORT=8080 JAVA_OPTS=""
EXPOSE 8080
USER 10001:10001
CMD ["sh","-c","exec java $JAVA_OPTS -Dserver.port=${PORT} -jar /app/app.jar"]
