# syntax=docker/dockerfile:1
# Generated by Koptan: Node 22 with yarn, starts with start script.
FROM node:22-bookworm-slim AS build
WORKDIR /app
RUN npm install -g corepack && corepack enable
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
COPY . .
RUN yarn install --frozen-lockfile

FROM node:22-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production PORT=8080
COPY --from=build --chown=1000:1000 /app /app
EXPOSE 8080
USER 1000:1000
CMD ["npm","run","start"]
