# syntax=docker/dockerfile:1
# Generated by Koptan: Node 20 with pnpm, starts with start script.
FROM node:20-bookworm-slim AS build
WORKDIR /app
RUN npm install -g corepack && corepack enable
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm run build
RUN pnpm prune --prod

FROM node:20-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production PORT=8080
COPY --from=build --chown=1000:1000 /app /app
EXPOSE 8080
USER 1000:1000
CMD ["npm","run","start"]
