# syntax=docker/dockerfile:1
# Generated by Koptan: Node 18 with npm, starts with server.js.
FROM node:18-bookworm-slim AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm prune --omit=dev

FROM node:18-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production PORT=3000
COPY --from=build --chown=1000:1000 /app /app
EXPOSE 3000
USER 1000:1000
CMD ["node","server.js"]
