# syntax=docker/dockerfile:1
# Generated by Koptan: Python 3.12 with pip, flask.
FROM python:3.12-slim AS build
ENV VIRTUAL_ENV=/opt/venv PATH=/opt/venv/bin:$PATH UV_PROJECT_ENVIRONMENT=/opt/venv \
    PIP_DISABLE_PIP_VERSION_CHECK=1
RUN python -m venv /opt/venv
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir gunicorn

FROM python:3.12-slim
ENV VIRTUAL_ENV=/opt/venv PATH=/opt/venv/bin:$PATH PYTHONUNBUFFERED=1 PORT=8080
WORKDIR /app
COPY --from=build /opt/venv /opt/venv
COPY . .
EXPOSE 8080
USER 10001:10001
CMD ["sh","-c","exec gunicorn app:application --bind 0.0.0.0:${PORT}"]
