# syntax=docker/dockerfile:1
# Generated by Koptan: Python 3.11 with poetry, fastapi.
FROM python:3.11-slim AS build
ENV VIRTUAL_ENV=/opt/venv PATH=/opt/venv/bin:$PATH UV_PROJECT_ENVIRONMENT=/opt/venv \
    PIP_DISABLE_PIP_VERSION_CHECK=1
RUN python -m venv /opt/venv
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false && poetry install --only main --no-root --no-interaction \
    && pip install --no-cache-dir uvicorn

FROM python:3.11-slim
ENV VIRTUAL_ENV=/opt/venv PATH=/opt/venv/bin:$PATH PYTHONUNBUFFERED=1 PORT=8080
WORKDIR /app
COPY --from=build /opt/venv /opt/venv
COPY . .
EXPOSE 8080
USER 10001:10001
CMD ["sh","-c","exec uvicorn app.main:api --host 0.0.0.0 --port ${PORT}"]
