# syntax=docker/dockerfile:1
# Generated by Koptan: Ruby 3.2, rails.
FROM ruby:3.2-slim AS build
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential git libpq-dev libyaml-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN bundle config set --local without 'development test' && bundle install --jobs 4 \
    && (SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile || true)

FROM ruby:3.2-slim
RUN apt-get update && apt-get install -y --no-install-recommends libpq5 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
ENV RAILS_ENV=production RACK_ENV=production RAILS_LOG_TO_STDOUT=1 \
    RAILS_SERVE_STATIC_FILES=1 BUNDLE_WITHOUT=development:test PORT=8080
COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --from=build --chown=10001:10001 /app /app
EXPOSE 8080
USER 10001:10001
CMD ["sh","-c","exec bundle exec rails server -b 0.0.0.0 -p ${PORT}"]
