# syntax=docker/dockerfile:1
# Generated by Koptan: Rust 1.80, binary hello.
FROM rust:1.80-bookworm AS build
WORKDIR /src
COPY . .
RUN cargo build --release --locked

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /src/target/release/hello /app/hello
ENV PORT=8080
EXPOSE 8080
USER 10001:10001
CMD ["/app/hello"]
