# syntax=docker/dockerfile:1
# Generated by Koptan: static site from public/ on nginx.
FROM nginxinc/nginx-unprivileged:1.27-alpine
USER root
RUN printf 'server {\n  listen 8080;\n  server_name _;\n  root /usr/share/nginx/html;\n  index index.html;\n  location / {\n    try_files $uri $uri/ /index.html;\n  }\n}\n' \
        > /etc/nginx/conf.d/default.conf
COPY --chown=101:101 public/ /usr/share/nginx/html/
ENV PORT=8080
EXPOSE 8080
USER 101:101
