---
apiVersion: koptan.felukka.org/v1alpha
kind: JavaApp 
metadata:
  name: projname
spec:
  source:
    repo: https://github.com/username/java-proj
    revision: main
---
apiVersion: koptan.felukka.org/v1alpha
kind: Slipway
metadata:
  name: projname 
spec:
  appRef:
    name: projname 
    kind: JavaApp
  image:
    # registry: docker.io
    name: username/feedme
    creds:
      username: username
      password: PAT
---
apiVersion: koptan.felukka.org/v1alpha
kind: Voyage
metadata:
  name: projname 
spec:
  slipwayRef:
    name: projname 
  port: 8080
  replicas: 2
  env:
    - name: ENV
      value: production
