package service

// defaultDockerignore keeps VCS data, local dependencies, build output and
// secrets out of the build context of a generated Dockerfile. It is only
// used when the build context has no .dockerignore of its own.
const defaultDockerignore = `# Generated by Koptan
.git
.gitignore
.dockerignore
**/.DS_Store
**/*.log
.env
.env.*
!.env.example
node_modules
**/node_modules
.npm
.yarn/cache
.pnpm-store
.venv
venv
**/__pycache__
**/*.pyc
.pytest_cache
.mypy_cache
target
bin
obj
.gradle
.idea
.vscode
coverage
tmp
`
