resources:
  - bases/koptan.felukka.sh_voyages.yaml
  - bases/koptan.felukka.sh_slipways.yaml
  - bases/koptan.felukka.sh_goapps.yaml
  - bases/koptan.felukka.sh_dotnetapps.yaml
  - bases/koptan.felukka.sh_javaapps.yaml
