resources:
  - bases/koptan.felukka.org_voyages.yaml
  - bases/koptan.felukka.org_slipways.yaml
  - bases/koptan.felukka.org_goapps.yaml
  - bases/koptan.felukka.org_dotnetapps.yaml
  - bases/koptan.felukka.org_javaapps.yaml
