resources:
  - bases/koptan.felukka.org_services.yaml
  - bases/koptan.felukka.org_cis.yaml
  - bases/koptan.felukka.org_cds.yaml
  - bases/koptan.felukka.org_ciplugins.yaml
  - bases/koptan.felukka.org_alerts.yaml
  - bases/koptan.felukka.org_selfservices.yaml
